ctrliq/ascender

.github/workflows/stage.yml
Docker needs to be set to version 6.1.3 or it fails to startup correctly for the build process
=> Fix docker version in build

awx/main/migrations/0191a_add_depot_credential.py, awx/main/models/credential/__init__.py
Support CIQ Depot credentials out of the box in Ascender. With this PR, users would no longer need to set up CIQ Depot credentials as a custom credential.
=> Add CIQ Depot credential

awx/settings/defaults.py
Rsyslog by default for Ascender is set to send a max size of 700k for the results data.  This can be problematic with playbooks that made changes with large file diffs or for servers that have over 2000 packages installed and you run package_facts on them.  So we will increase to 25M to ensure we don't improperly drop data in the future.
=> Update defaults.py to increase rsyslog max size

requirements/requirements.in, requirements/requirements.txt
Update jinja2 to fix CVE-2024-56326 and CVE-2024-56201
=> Update jinja2 to fix CVE-2024-56326 and CVE-2024-56201

Makefile, requirements/requirements.in, requirements/requirements.txt
Correcting injection bug in Mercurial that affected PIP.  Does not affect our base.  Removing for scanning purposes.
=> Updating PIP to version 23.3 for CVE-2023-5752

Makefile, awx/ui/package-lock.json, requirements/requirements.in, requirements/requirements.txt
Correcting injection bug in Mercurial that affected PIP. Does not affect our base. Removing for scanning purposes.
=> Update PIP to 23.3 to address Mercurial Injection CVE-2023-5752

Makefile, requirements/requirements.in, requirements/requirements.txt
* Resolve issues with setuptools.  Addresses CVE-2024-6345
* Introduces deprecation warnings around pkg_resources which will eventually have to be replace.
=> Udating for setuptools to address CVE-2024-6345

Makefile, awx/ui/package-lock.json, requirements/requirements.in, requirements/requirements.txt
[Udating for setuptools to address](https://github.com/ctrliq/ascender/commit/f692fd7422ee14c6cef93a4a12f8c8a2fef97571) https://github.com/advisories/GHSA-cx63-2mw6-8hw5
After this commit, we need to investigate the replacement of pkg_resources.
=>  Udating for setuptools to address CVE-2024-6345 

awx/ui/package-lock.json, awx/ui/package.json
Updating `http-proxy-middleware` to version `2.0.7` to fix CVE-2024-21536
Tested locally running the node container before and after the change in browser and didn't see any errors
=> Updating `http-proxy-middleware` to version `2.0.7` CVE-2024-21536

awx/main/utils/external_logging.py
Add an authorization header for Ledger if a token is set. This will allow us to change ledger to use tokens instead of setting trusted servers.
=> Ledger authentication

awx/main/utils/external_logging.py, awx/main/utils/formatters.py, awx/main/utils/handlers.py, tools/ansible/roles/dockerfile/files/rsyslog.conf
This change updates rsyslog to use the imptcp input module over the legacy socket input module.  It does this to avoid Message too long errors (Errno 90) that occur with large packet sizes.
- Other - Logging
=> Fix Issue #51 - Unable to upload more than 1500 packages to ledger due to rsyslog defaults

awx/main/utils/external_logging.py
Fixes this error
```
tools_awx_1       | rsyslogd: imptcp: error while binding unix socket: Address already in use
tools_awx_1       | rsyslogd: activation of module imptcp failed 
```
=> Fix rsyslog rebind issue

Makefile
Replace the deprecated usage of "docker-compose" with "docker compose"
=> Replace Docker-compose with "docker compose"

tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
With the crackdown on unauthenticated pulls on docker.io, move to using an image mirror.
=> Docker Image Mirror

awx/__init__.py, awx/main/db/profiled_pg/base.py, awx/main/models/credential/__init__.py, awx/main/utils/common.py, awxkit/awxkit/cli/client.py, tools/ansible/roles/dockerfile/templates/Dockerfile.j2, tools/docker-compose/awx-manage, tools/scripts/firehose.py
This resolves the pkg_resources deprecation warnings.
Commits pulled from upstream minus a few minor changes as we are on an older version of python (utilize importlib_metadata instead of importlib.metadata)
Upstream
https://github.com/ansible/awx/commit/e68370f2aa2dc0fb435de39835beb0edc1c55225
https://github.com/ansible/awx/commit/3edaaebba22ba8137340eace28b14deedc7da69b
=> Migrate away from pkg_resources as it's deprecated

requirements/requirements.in, requirements/requirements.txt
Updating cryptography>=44.0.1 to fix CVE-2024-12797
https://github.com/ctrliq/ascender/security/dependabot/120
- API
```
24.0.4
```
=> Updating cryptography>=44.0.1 to fix CVE-2024-12797

requirements/requirements.in, requirements/requirements.txt
After updating cryptography>=44.0.1 pip build fails due to `pyopenssl` needing update as well
- API
```
24.0.4
```
```
```
=> Fixing pyopenssl dependencies

awx/ui/package-lock.json, awx/ui/package.json
Upgrade http-proxy-middleware to version 2.0.9 to resolve 2 CVEs
CVE-2025-32996
CVE-2025-32997
=> Upgrade http-proxy-middleware to resolve CVEs

awx/main/conf.py, awx/main/models/unified_jobs.py, awx/main/utils/formatters.py, awx/settings/defaults.py, tools/docker-compose/docs/logstash.md
Pulls in 2 Upstream commits to allow sending job_lifecycle events to external loggers
Remove json formatter for job lifecycle
Upstream commmit https://github.com/ansible/awx/commit/d06ce8f9119267862fcca00fc85af3a9f323d61c
Send job_lifecycle logs to external loggers
Upstream commit https://github.com/ansible/awx/commit/5944d041e622956dba38dac791ace826134d1f55
=> Send job_lifecycle logs to external loggers

awx/ui/src/components/AddRole/SelectResourceStep.js
Fixing a bug introduced during `lingui4` migration where when trying to add user to team permissions the `fetchItems` function is called in a loop regardless of the response received form the back end.
This pr is fixing that behavior 
- UI
```
25.0.0
```
To reproduce the issue: 
Go to Teams → Select a team → click Access tap → click Add → Select Users and click Next 
You will now observe that users API is keep called even though it returns 200 first time around 
[Add User Roles to Team.webm](https://github.com/user-attachments/assets/21a83f18-48a3-4930-b4ff-0d9321128e52)
=> Continue reload when add user permissions to team

awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListItem.js
When workflow is pending approval using the approval buttons in https://localhost:3001/#/workflow_approvals is not working for both approve and deny. Error: 
```
WorkflowApprovalButton.js:28 Uncaught (in promise) TypeError: onHandleToast is not a function
at handleApprove (WorkflowApprovalButton.js:28:1)
handleApprove	@	WorkflowApprovalButton.js:28
await in handleApprove		
onClick	@	WorkflowApprovalButton.js:40
```
This change fixes that 
- UI
```
25.0.0
```
=> Adding toast handler to fix errors when using list approve or deny buttons

awx/ui/src/api/models/Root.js
Error caused by upstream PR #14020 that was added to support running in a sub directory (which that PR is actually incomplete, as there are a lot of hard coded paths still (like redirects to /login).
GET https://ASCENDERHOST:3001/api/login/api/v2/config/
After logging in, React is appending the "next" url to the "current" url as its not an absolute path.  This happens when we initially call /api/login/ so that we end up trying to call /api/login/api/v2/config when it redirects.  This only happens during the login process.  I have stepped through the javascript execution and it happens in React, not in our code, so this is a small workaround to fix it.  This will still support running Ascender in a sub directory, but will will force an absolute path based upon the current window path …
=> Fix 404 error when logging in

awx/ui/src/components/LabelLists/LabelListItem.js, awx/ui/src/components/LabelLists/LabelLists.js, awx/ui/src/routeConfig.js, awx/ui/src/screens/Labels/Labels.js, awx/ui/src/screens/Labels/index.js
We create a new Menu item to display all the Job/Workflow Template labels.  From here, when clicked, we can then redirect to a search for that Label on the Template.
Simplistic way of doing it, but works fine with the current labeling system.
In the future, we will create methods for more easily associating or disassociating templates in bulk.
=> Start using Labels as Folders

.github/workflows/devel_images.yml
Trying to force packages to a lower version so we can use SHA checksums as versions.
=> Attempt to force packaging version to allow SHA versions

awx/ui/src/components/About/About.js
Resolves #54
Changes to not use the trademark instead insert a DIV that allows us to split the About Copyrights onto new lines.
=> Fix the about page

requirements/requirements.in, requirements/requirements.txt
This also upgrades aiohappyeyeballs and aiosignal as dependencies
=> Upgrade aiohttp to resolve CVE-2025-53643

awx/ui/src/screens/Login/Login.js
Resolves #135
This modal is unnecessary, and should be removed.
=> Remove alert modal if custom login settings can't be fetched

awx/ui/src/components/JobList/JobList.js, awx/ui/src/components/LaunchButton/LaunchButton.js, awx/ui/src/hooks/useWebsocket.js, awx/ui/src/screens/InstanceGroup/Instances/InstanceList.js, awx/ui/src/screens/Job/JobOutput/connectJobSocket.js, awx/ui/src/screens/Job/JobOutput/shared/OutputToolbar.js
The websockets have been troublesome for a long time, even upstream.
The issue seemed to stem from using a global for the websocket, whereas we should instead be storing the socket in a ref and manage its lifecycle ourselves.  That way we can ensure to always close the previous socket before opening a new one.  We also add in a tiny delay on initialization, which seems to fix a few of the "could not connect" errors (it would then retry and connect, but that took longer than adding a delay).
Now when launching a job, its output seems to fully load and complete without issue.
Also starting to clean up some of these errors by ensuring things are mounted before trying to update them.  There are a lot more to fix, but its a start.
> "Can't perform a React state update on an unmounted …
=> Fix some websocket issues and memory leaks in asyncs

awx/ui/Dockerfile, awx/ui/package-lock.json, awx/ui/package.json, tools/ansible/roles/dockerfile/templates/Dockerfile.j2
We purposely set the package.json to specify a slightly lower node version, as that is what Rocky9 installs by default.  You still get the latest via npm, but that resolves a warning when running in Dev.
This gets us up to a supported version of NodeJS.
=> Upgrade to latest Node 20 LTS

awx/main/tasks/jobs.py
=> Setting with ANSIBLE_BASE_ prefix does not need to be added to env var for job execution
