- requirements/requirements.txt
Fixing a change for requirement.txt that got reversed before commit
> Fix requirements.txt

- .github/actions/awx_devel_image/action.yml
- Makefile
- awx/__init__.py
- awx/conf/settings.py
- awx/conf/tests/unit/test_settings.py
- awx/main/utils/common.py
- awx/ui/src/screens/Setting/MiscSystem/MiscSystemDetail/MiscSystemDetail.js
- awx/ui/src/util/getDocsBaseUrl.js
- awx/ui/src/util/getDocsBaseUrl.test.js
- awx_collection/plugins/modules/schedule.py
- awx_collection/tests/integration/targets/schedule/tasks/main.yml
- requirements/README.md
- tools/docker-compose/README.md
- tools/docker-compose/ansible/smoke-test.yml
- tools/docker-compose/ansible/templates/ldap_settings.json.j2
- tools/scripts/get_next_release.py
Also added a small change to remove the read only display of a few settings that we already removed from the edit screens.
> Sync to Upstream 23.2.0

- Makefile
- awx/api/views/__init__.py
- awx/main/access.py
- awx/main/credential_plugins/dsv.py
- awx/main/migrations/0006_v320_release.py
- awx/main/migrations/0050_v340_drop_celery_tables.py
- awx/main/migrations/0113_v370_event_bigint.py
- awx/main/migrations/0144_event_partitions.py
- awx/main/migrations/0185_move_JSONBlob_to_JSONField.py
- awx/main/migrations/0186_drop_django_taggit.py
- awx/main/migrations/_sqlite_helper.py
- awx/main/models/__init__.py
- awx/main/models/mixins.py
- awx/main/tests/functional/test_migrations.py
- awx/main/tests/functional/test_rbac_user.py
- awx/main/utils/licensing.py
- awx_collection/plugins/modules/credential.py
- awx_collection/tests/integration/targets/credential/tasks/main.yml
- requirements/requirements_dev.txt
- tools/docker-compose/ansible/roles/vault/tasks/initialize.yml
- tox.ini
> Sync to Upstream 23.5.0

- .github/workflows/promote.yml
- awx/main/wsrelay.py
Fixing wsrelay connection loop
> Sync to Upstream 23.5.1

- Makefile
- awx/main/dispatch/worker/base.py
- awx/main/models/notifications.py
- awx/main/routing.py
- awx/main/tasks/callback.py
- awx/main/tasks/jobs.py
- awx/main/wsrelay.py
- awx_collection/test/awx/test_notification_template.py
- awxkit/setup.py
- licenses/Cython.txt
- requirements/requirements.in
- requirements/requirements.txt
- requirements/updater.sh
- tools/ansible/roles/dockerfile/templates/Dockerfile.j2
- tools/docker-compose/ansible/roles/sources/templates/nginx.locations.conf.j2
- tools/sosreport/controller.py
> Sync to Upstream 23.8.1

- .github/workflows/stage.yml
> Download requests to fix bug during build

- MANIFEST.in
- Makefile
- awx/urls.py
> Testing removing ui next

- awx/ui/package-lock.json
- Breaking Change 
- New or Enhanced Feature
- API
- UI
- Collection
- CLI
- Docs
- Other
```
```
```
```
> Fix 2 new vulnerabilities in dependent libraries

- awx/api/views/mixin.py
- awx/api/views/organization.py
- awx/main/management/commands/run_wsrelay.py
- awx/main/wsrelay.py
- awx/ui/package-lock.json
- awx/ui/package.json
- awx/ui/src/screens/Dashboard/DashboardGraph.js
- requirements/requirements.in
- requirements/requirements.txt
> Django / Dompurify

- requirements/requirements.in
- requirements/requirements.txt
Upgrating aiohttp>=3.10.11  fixing  CVE-2024-52304
Simple container check and UI
> Upgrating aiohttp>=3.10.11  fixing  CVE-2024-52304

- awx/ui/package-lock.json
path-to-regexp: CVE-2024-52798,
nanoid: CVE-2024-55565,
cross-spawn: CVE-2024-21538,
express: CVE-2024-47764
> Update NPM Packages to Resolve 4 Vulnerabilities:

- requirements/requirements.in
- requirements/requirements.txt
> Merging CVE Fixes from Develop to Main

- awx/ui/package-lock.json
CVEs fixed:
- CVE-2025-27789
- CVE-2024-11831
ran `npm audit fix`
issues fixed 
```
3,20d2
< @babel/helpers  <7.26.10
< Severity: moderate
< Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
< fix available via `npm audit fix`
< node_modules/@babel/helpers
< 
< @babel/runtime  <7.26.10
< Severity: moderate
< Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
< fix available via `npm audit fix`
< node_modules/@babel/runtime
< 
< @babel/runtime-corejs3  <7.26.10
< Severity: moderate
< Babel has inefficient RexExp complexity in generated code with .replace when …
```
> Update NPM Packages to Resolve CVE-2024-11831 and CVE-2025-27789

- requirements/requirements.in
- requirements/requirements.txt
Update Django to fix CVE-2025-26699
- API
```
24.0.4
```
> Update Django to fix CVE-2025-26699

- awx/ui/package-lock.json
- awx/ui/package.json
- requirements/requirements.in
- requirements/requirements.txt
> Rebase from main

- awx/main/utils/formatters.py
Simpler way of sending the Tower Base URL and the Unique Install UUID to Log aggregators
> Add Install UUID and URL to log data

- awx/api/generics.py
- awx/settings/defaults.py
- awx/sso/views.py
Resolves #48
Patch from Upstream
https://github.com/ansible/awx/pull/15100
> Add option for SAMESITE

- awx/main/wsrelay.py
Upstream https://github.com/ansible/awx/pull/15094
> Fixed missing fstring from wsrelay logging

- awx/main/conf.py
Verifies that the urls entered conform to proper addresses
> Adding CSRF Validation for schemas - Upstream PR 15027

- awx/ui/src/screens/Instances/InstancePeers/InstancePeerList.js
Upstream PR # 15108
Will have to wait until image is created to test, as can only add additional instances to Kub environments.
> Fix instance peering pagination

- awx/conf/fields.py
Upstream PR # 15144
We already upgraded to the latest version of djangorestframework, so definitely need this fix in there.
> Fix issue with latest DRF (lists are capitalized)

- awx/ui/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateList.js
> Fix notification name search

- .gitignore
- Makefile
- tools/docker-compose/ansible/roles/sources/defaults/main.yml
- tools/docker-compose/ansible/roles/sources/tasks/main.yml
- tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
- tools/docker-compose/editable_dependencies/README.md
- tools/docker-compose/editable_dependencies/install.sh
Editable dependencies in docker compose development environment - Upstream PR # 14979
Remove links from docker-compose template - Upstream PR # 15386
Fix depends_on for awx devel when editable dependencies is enabled - Upstream PR # 15393
> Docker Compose links removal + add editable dependencies

- awx/main/tasks/facts.py
- awx/main/tasks/jobs.py
- awx/main/tests/data/projects/facts/clear.yml
- awx/main/tests/data/projects/facts/gather.yml
- awx/main/tests/data/projects/facts/no_op.yml
- awx/main/tests/unit/models/test_jobs.py
- awx/main/tests/unit/tasks/test_jobs.py
> Facts are unintentionally deleted when the inventory is modified during a job execution

- requirements/requirements.in
- requirements/requirements.txt
Minor update.  Requirements Updater ran.  Containers successfully rebuild after updating.
> Update django to resolve CVE-2025-48432

- awx/playbooks/project_update.yml
Upstream PR #15017
You notice this when using an EE with ansible core > 2.15 but less than 2.17 (ansible but was fixed in 2.17)
>  Address first_found skip bug

- .github/workflows/devel_images.yml
I really dislike PEP 440 at this point.
> Try using the .dev extension

- .github/workflows/devel_images.yml
Also allow rebuilds on feature branches
> Use short SHA

- requirements/requirements.in
- requirements/requirements.txt
Seems it affected other areas too which were fixed in this new version
> Update django to 4.2.23, more work was done on CVE-2025-48432

- tools/docker-compose/Dockerfile-logstash
- tools/elastic/elasticsearch/Dockerfile
- tools/elastic/kibana/Dockerfile
- tools/elastic/logstash/Dockerfile
> Update kibana, etc... images to latest

- Makefile
- tools/docker-compose/ansible/roles/sources/defaults/main.yml
Pinning version because of upstream issues
> Fix receptor image in a few more places

- awx/ui/package-lock.json
Added 92 packages, removed 218 packages, changed 133 packages
> Update Nodejs packages

- awx/ui/package-lock.json
- awx/ui/package.json
Axios is vulnerable to DoS attack through lack of data size check
> Update axios to 1.12 to resolve CVE-2025-58754

- awx/main/fields.py
> fix: maintain order of insertions into m2m relationship tables
